<a href="https://colab.research.google.com/github/ismael-rtellez/Matrix_Product_Implementation_Series/blob/main/Matrix_product_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem 1: Matrix product is calculated manually

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])    #load the matrix array
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])     #load the matrix array

a00xb00 = a_ndarray[0, 0] * b_ndarray[0, 0] #multiply the first value of the first row of matrix a with the first value of the first column of matrix b
a01xb10 = a_ndarray[0, 1] * b_ndarray[1, 0] #multiply the second value of the first row of matrix a with the second value of the first column of matrix b
a02xb20 = a_ndarray[0, 2] * b_ndarray[2, 0] #multiply the third value of the first row of matrix a with the third value of the first column of matrix b
res_ab00 = a00xb00 + a01xb10 + a02xb20      #We sum up all the results obtained
a00xb01 = a_ndarray[0, 0] * b_ndarray[0, 1] #multiply the first value of the first row of matrix a with the first value of the second column of matrix b
a01xb11 = a_ndarray[0, 1] * b_ndarray[1, 1] #multiply the second value of the first row of matrix a with the second value of the second column of matrix b
a02xb21 = a_ndarray[0, 2] * b_ndarray[2, 1] #multiply the third value of the first row of matrix a with the third value of the second column of matrix b
res_ab01 = a00xb01 + a01xb11 + a02xb21      #We sum up all the results obtained
a00xb02 = a_ndarray[0, 0] * b_ndarray[0, 2] #multiply the first value of the first row of matrix a with the first value of the third column of matrix b
a01xb12 = a_ndarray[0, 1] * b_ndarray[1, 2] #multiply the second value of the first row of matrix a with the second value of the third column of matrix b
a02xb22 = a_ndarray[0, 2] * b_ndarray[2, 2] #multiply the third value of the first row of matrix a with the third value of the third column of matrix b
res_ab02 = a00xb02 + a01xb12 + a02xb22      #We sum up all the results obtained

a10xb00 = a_ndarray[1, 0] * b_ndarray[0, 0] #multiply the first value of the second row of matrix a with the first value of the first column of matrix b
a11xb10 = a_ndarray[1, 1] * b_ndarray[1, 0] #multiply the second value of the second row of matrix a with the second value of the first column of matrix b
a12xb20 = a_ndarray[1, 2] * b_ndarray[2, 0] #multiply the third value of the second row of matrix a with the third value of the first column of matrix b
res_ab10 = a10xb00 + a11xb10 + a12xb20      #We sum up all the results obtained
a10xb01 = a_ndarray[1, 0] * b_ndarray[0, 1] #multiply the first value of the second row of matrix a with the first value of the second column of matrix b
a11xb11 = a_ndarray[1, 1] * b_ndarray[1, 1] #multiply the second value of the second row of matrix a with the second value of the second column of matrix b
a12xb21 = a_ndarray[1, 2] * b_ndarray[2, 1] #multiply the third value of the second row of matrix a with the third value of the second column of matrix b
res_ab11 = a10xb01 + a11xb11 + a12xb21      #We sum up all the results obtained
a10xb02 = a_ndarray[1, 0] * b_ndarray[0, 2] #multiply the first value of the second row of matrix a with the first value of the third column of matrix b
a11xb12 = a_ndarray[1, 1] * b_ndarray[1, 2] #multiply the second value of the second row of matrix a with the second value of the third column of matrix b
a12xb22 = a_ndarray[1, 2] * b_ndarray[2, 2] #multiply the third value of the second row of matrix a with the third value of the third column of matrix b
res_ab12 = a10xb02 + a11xb12 + a12xb22      #We sum up all the results obtained

a20xb00 = a_ndarray[2, 0] * b_ndarray[0, 0] #multiply the first value of the third row of matrix a with the first value of the first column of matrix b
a21xb10 = a_ndarray[2, 1] * b_ndarray[1, 0] #multiply the second value of the third row of matrix a with the second value of the first column of matrix b
a22xb20 = a_ndarray[2, 2] * b_ndarray[2, 0] #multiply the third value of the third row of matrix a with the third value of the first column of matrix b
res_ab20 = a20xb00 + a21xb10 + a22xb20      #We sum up all the results obtained
a20xb01 = a_ndarray[2, 0] * b_ndarray[0, 1] #multiply the first value of the third row of matrix a with the first value of the second column of matrix b
a21xb11 = a_ndarray[2, 1] * b_ndarray[1, 1] #multiply the second value of the third row of matrix a with the second value of the second column of matrix b
a22xb21 = a_ndarray[2, 2] * b_ndarray[2, 1] #multiply the third value of the third row of matrix a with the third value of the second column of matrix b
res_ab21 = a20xb01 + a21xb11 + a22xb21      #We sum up all the results obtained
a20xb02 = a_ndarray[2, 0] * b_ndarray[0, 2] #multiply the first value of the third row of matrix a with the first value of the third column of matrix b
a21xb12 = a_ndarray[2, 1] * b_ndarray[1, 2] #multiply the second value of the third row of matrix a with the second value of the third column of matrix b
a22xb22 = a_ndarray[2, 2] * b_ndarray[2, 2] #multiply the third value of the third row of matrix a with the third value of the third column of matrix b
res_ab22 = a20xb02 + a21xb12 + a22xb22      #We sum up all the results obtained

#We arrange the results in the resulting matrix according to their position given by the rules of multiplication operation
result_ndarray = np.array(
    [[res_ab00, res_ab01, res_ab02], [res_ab10, res_ab11, res_ab12], [res_ab20, res_ab21, res_ab22]])
print(result_ndarray)   #We print the result

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])  #load the matrix array
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])   #load the matrix array

#A way to do all of the above, only shorter and faster.
r_0_0 = ((-1*0)+(2*0)+(3*2))
r_0_1 = ((-1*2)+(2*2)+(3*9))
r_0_2 = ((-1*1)+(2*-8)+(3*-1))
r_1_0 = ((4*0)+(-5*0)+(6*2))
r_1_1 = ((4*2)+(-5*2)+(6*9))
r_1_2 = ((4*1)+(-5*-8)+(6*-1))
r_2_0 = ((7*0)+(8*0)+(-9*2))
r_2_1 = ((7*2)+(8*2)+(-9*9))
r_2_2 = ((7*1)+(8*-8)+(-9*-1))

result_ndarray = np.array([[r_0_0, r_0_1, r_0_2], [r_1_0, r_1_1, r_1_2], [r_2_0, r_2_1, r_2_2]])
print(result_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## Problem 2: Calculation by NumPy function

In [3]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])  #load the matrix array
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])   #load the matrix array

result_matmul = np.matmul(a_ndarray, b_ndarray)   #We call to the function np.matmul and give the two matrixs as data
print(result_matmul)    #We print the result of the funtcion matmul

print()

result_dot = np.dot(a_ndarray, b_ndarray)         #We call to the function np.dot and give the two matrixs as data
print(result_dot)       #We print the result of the funtcion dot

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## Problem 3: Implementation of calculation of a certain element

In [4]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])  #load the matrix array
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#Inicializate the data with valor of zero
i = 0
r_0_0 = 0; r_0_1 = 0; r_0_2 = 0
r_1_0 = 0; r_1_1 = 0; r_1_2 = 0
r_2_0 = 0; r_2_1 = 0; r_2_2 = 0

#In a while we perform the multiplication operations using a
#counter “i” in order to move through the different data of the two matrices
while(i < 3):
  ab_00 = r_0_0 + (a_ndarray[0, i] * b_ndarray[i, 0])
  r_0_0 = ab_00
  ab_01 = r_0_1 + (a_ndarray[0, i] * b_ndarray[i, 1])
  r_0_1 = ab_01
  ab_02 = r_0_2 + (a_ndarray[0, i] * b_ndarray[i, 2])
  r_0_2 = ab_02
  ab_10 = r_1_0 + (a_ndarray[1, i] * b_ndarray[i, 0])
  r_1_0 = ab_10
  ab_11 = r_1_1 + (a_ndarray[1, i] * b_ndarray[i, 1])
  r_1_1 = ab_11
  ab_12 = r_1_2 + (a_ndarray[1, i] * b_ndarray[i, 2])
  r_1_2 = ab_12
  ab_20 = r_2_0 + (a_ndarray[2, i] * b_ndarray[i, 0])
  r_2_0 = ab_20
  ab_21 = r_2_1 + (a_ndarray[2, i] * b_ndarray[i, 1])
  r_2_1 = ab_21
  ab_22 = r_2_2 + (a_ndarray[2, i] * b_ndarray[i, 2])
  r_2_2 = ab_22
  i += 1

#We arrange the results in the resulting matrix according to their positions
result_ndarray = np.array([[r_0_0, r_0_1, r_0_2], [r_1_0, r_1_1, r_1_2], [r_2_0, r_2_1, r_2_2]])
print(result_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## Problem 4: Creating a function that performs matrix multiplication

In [5]:
import numpy as np

def mat_mul(A, B):        #We create the function
  rows_A, columns_A = A.shape   #We take out the value of the dimensions of each matrix
  rows_B, columns_B = B.shape   #Rows and Columns
  result = np.zeros((rows_A, columns_B)).astype(np.int64)   #Create one matrix of zeros for the results
  for i in range(len(A)):                   #We go through the rows of matrix A
    for j in range(len(B[0])):              #We go through the columns of matrix B
      for k in range(len(B)):               #We go through the rows of matrix B
        result[i, j] += A[i, k] * B[k, j]   #We perform the operations to obtain a value of the resulting matrix
  return result                             #this is repeated for all the values of the resultant matrix

matrix_a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]]) #load the matrix array
matrix_b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#We call the function assigning the matrices as data
matrix_c = mat_mul(matrix_a, matrix_b)
print(matrix_c)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## Problem 5: Judge the input whose calculation is not defined

In [6]:
import numpy as np

#We do the same function as in the previous exercise, we only add an “if” to corroborate that the matrix can be multiplied
def mat_mul_2(A, B):
  rows_A, columns_A = A.shape
  rows_B, columns_B = B.shape
  #We check if the rule that the multiplication of matrices is fulfilled is satisfied
  if (columns_A == rows_B):       #The columns of matrix A must be equal to the rows of matrix B
  #If it is fulfilled, proceed as in the previous exercise
    result = np.zeros((rows_A, columns_B)).astype(np.int64)
    for i in range(len(A)):
      for j in range(len(B[0])):
        for k in range(len(B)):
          result[i, j] += A[i, k] * B[k, j]
    return result
  #If this is not the case, a message is printed stating that it is not possible to multiply the matrices
  else:
    print("Invalid entries, the operation cannot be performed because the number of columns and rows does not correspond.")

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])    #load the matrix array
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

#We call the function assigning the matrices as data
matrix_result = mat_mul_2(d_ndarray, e_ndarray)
print(matrix_result)

Invalid entries, the operation cannot be performed because the number of columns and rows does not correspond.
None


## Problem 6: Transposition

In [9]:
import numpy as np

#We do the same function as in the previous exercise, including the “if” to corroborate that the matrix can be multiplied
#But this time, in order to fulfill the “if” condition, we will transpose a matrix so that we can perform multiplication
def mat_mul_2(A, B):
  rows_A, columns_A = A.shape
  rows_B, columns_B = B.shape
  #We check whether the columns of A are the same as the rows of B
  if (columns_A == rows_B):
    result = np.zeros((rows_A, columns_B)).astype(np.int64)
    for i in range(len(A)):
      for j in range(len(B[0])):
        for k in range(len(B)):
          result[i, j] += A[i, k] * B[k, j]
    return result
  #In case the “if” condition is not met, we will transpose a matrix
  else:
    if (matrix_t == 1):
      #If we gave the variable “matrix_t” the value of 1, let's transpose the first matrix
      T = np.transpose(d_ndarray)   #we transpose the matrix using np.transpose and telling it which matrix to transpose
      rows_T, columns_T = T.shape   #We take out the value of the dimensions of the transposed matrix
      result = np.zeros((rows_T, columns_B)).astype(np.int64)   #Create one matrix of zeros for the results using the values of the transposed matrix
      #The rest is the same as in previous excercises using the transposed matrix
      for i in range(len(T)):
        for j in range(len(B[0])):
          for k in range(len(B)):
            result[i, j] += T[i, k] * B[k, j]
      return result
    else:
      #If we give it any other value we will transpose the second matrix
      T = np.transpose(e_ndarray)   #we transpose the matrix using np.transpose and telling it which matrix to transpose
      rows_T, columns_T = T.shape   #We take out the value of the dimensions of the transposed matrix
      result = np.zeros((rows_A, columns_T)).astype(np.int64)   #Create one matrix of zeros for the results using the values of the transposed matrix
      #The rest is the same as in previous excercises using the matrix transposed
      for i in range(len(A)):
        for j in range(len(T[0])):
          for k in range(len(T)):
            result[i, j] += A[i, k] * T[k, j]
      return result

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])    #load the matrix array
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
matrix_t = 1      #We give a value for choosing which matrix to transpose

#We call the function assigning the matrices as data
matrix_result = mat_mul_2(d_ndarray, e_ndarray)
print(matrix_result)

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
